apiVersion: v1
kind: Service
metadata:
  name: {{ template "web-web.fullname" . }}
  labels:
    app: {{ template "web-web.name" . }}
    chart: {{ template "web-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "web-web.name" . }}
    release: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "web-web.fullname" . }}-static
  labels:
    app: {{ template "web-web.name" . }}-static
    chart: {{ template "web-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "web-web.name" . }}-static
    release: {{ .Release.Name }}
